### ISSUE TITLE
Only highlight exact words

### ISSUE THREAD

**Issue by havardl** [Astray-git/vue-highlight-words#1]
Hi, thanks for a great package! 

Is it possible to only highlight exact words and not parts of a longer word? E.g. in the demo, the search term 'per' highlights the beginning of perhaps.

**Comment by Astray-git** [comment]
You can turn `autoEscape` off (it's `true` in the demo), then use search word with Regexp [word boundary](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-word-boundary) .
Try put `'\\bper\\b'` in `searchWords`.

**Comment by havardl** [comment]
Worked great, thank you @Astray-git!

**Comment by edum18** [comment]
@Astray-git unfortunately it doesn't work when the words have parenthesis

**Comment by Astray-git** [comment]
@edum18 You can try set `autoEscape` true
