### ISSUE TITLE
Does it support Vue 3.x?

### ISSUE THREAD

**Issue by bietkul** [Astray-git/vue-highlight-words#24]

**Comment by Astray-git** [comment]
Not yet. 3.x has changes on render function api.

**Comment by kawamataryo** [comment]
Hi.
I've created Vue3 supported highlighter library while referencing [vue-text-highlighter](https://github.com/kawamataryo/vue-word-highlighter) .
You can use it if you want.

https://github.com/kawamataryo/vue-word-highlighter

**Comment by Astray-git** [comment]
Please upgrade to v2.x
