### ISSUE TITLE
CDN usage without auto-register to Vue

### ISSUE THREAD

**Issue by bernardoduarte** [Astray-git/vue-highlight-words#5]
This package when used with a CDN like [jsDelivr](https://www.jsdelivr.com/package/npm/vue-highlight-words) does not auto register itself into Vue when loaded.

```html
<script src="https://cdn.jsdelivr.net/npm/vue-highlight-words@1.0.0/dist/vue-highlight-words.umd.js" integrity="sha256-392/JhDomBEByaaucvrkQgjQjfexDFyYI8WZguRMIp4=" crossorigin="anonymous"></script>
```

It requires something like the following before Vue initialization:
```html
<script>
Vue.component('Highlight', vueHighlightWords.default);
</script>
```
Or when initializing Vue:
```html
<script>
new Vue({
	components: {
		Highlight: vueHighlightWords.default
	},
	el: '#app',
	data: () => ({...})
})
</script>
```
If this is the desired behavior then please add it to the docs ;D

**Comment by Astray-git** [comment]
This should be fixed on 1.2.0
