### ISSUE TITLE
Apply "global" highlight styles?

### ISSUE THREAD

**Issue by swthate** [Astray-git/vue-highlight-words#7]
Is there any way to apply `highlightStyle` on a sort of global scope so any time `<Highlighter>` is used the same custom highlight styles get used automatically? I'd prefer not to have to declare the four same styles each time I use the component throughout the UI if possible...

Thanks!

**Comment by Astray-git** [comment]
Try use `highlightClassName`

**Comment by swthate** [comment]
I was wondering why in the world that wasn't working... but I had a typo: `highlighClassName`. Missing the `t`. Oops! Now it's working, thanks :)
