### ISSUE TITLE
Allow html rendar

### ISSUE THREAD

**Issue by asifkhankadiwala** [Astray-git/vue-highlight-words#8]
In unhighlighted text html print as a text. Is there any way to make html appear as it is instead of text? 
I have checked highlight-words-core and it support it. https://codesandbox.io/s/ykwrzrl6wx
![image](https://user-images.githubusercontent.com/30252847/63317526-db80ab00-c330-11e9-8e22-0d1b2e69e69d.png)

**Comment by Astray-git** [comment]
This component is created to avoid rendering text content in Vue using `v-html` or `el.innerHtml`.

As warning in [doc](https://vuejs.org/v2/guide/syntax.html#Raw-HTML):
> Dynamically rendering arbitrary HTML on your website can be very dangerous because it can easily lead to XSS vulnerabilities. Only use HTML interpolation on trusted content and never on user-provided content.

**Comment by asifkhankadiwala** [comment]
Yes, I can understand that. Because of that when i submit data i simply remove all html tag and submit emoji code instead of html.

**Comment by Astray-git** [comment]
How about put a regex for your emoji code in `searchWords` then handle them as highlight chunks:
```vue
<HighlightWords
  ...
  v-slot="{ children }">
  <Emoji v-if="isEmoji(children)" :code="children"/>
  <mark v-else>{{children}}</mark>
</HighlightWords>

```

**Comment by asifkhankadiwala** [comment]
Thank for the solution,
